### ISSUE TITLE
v8::Context::New() V8 is no longer usable

### ISSUE THREAD

**Issue by JeDa** [LifeMushroom/Modular-Node.js-IRC-Bot#45]
Huh, I can't start the bot :/
That's what I get:

user@vps187670:~/MushroomBlock$ node app.js
FATAL ERROR: v8::Context::New() V8 is no longer usable
Aborted

**Comment by LifeMushroom** [comment]
Why do you need to run it as a daemon anyway?

**Comment by JeDa** [comment]
It does either from main.js and app.js

**Comment by JeDa** [comment]
(later of 28 days)
never mind, it was the VPS fucking up
